export default {
  commands: '명령',
  'code-review': '코드 리뷰',
  'followup-suggestions': '후속 제안',
  'tool-use-summaries': 'Tool-Use Summaries',
  'sub-agents': 'SubAgents',
  arena: 'Agent Arena',
  skills: '스킬',
  memory: '메모리',
  headless: 'Headless Mode',
  'dual-output': '듀얼 출력',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': '승인 모드',
  mcp: 'MCP',
  lsp: 'LSP (Language Server Protocol)',
  'token-caching': '토큰 캐싱',
  sandbox: 'Sandboxing',
  language: 'i18n',
  channels: '채널',
  hooks: '훅',
  'status-line': '상태 줄',
  'scheduled-tasks': '예약된 작업',
  tips: 'Contextual Tips',
};
